//
// Created by User on 19/11/2023.
//

#ifndef NOTSECURESECUREPWDMANAGER_PROGRAM_OPTIONS_H
#define NOTSECURESECUREPWDMANAGER_PROGRAM_OPTIONS_H
int ProgramOptions(int argc, char* argv[]);
#endif //NOTSECURESECUREPWDMANAGER_PROGRAM_OPTIONS_H
